"""empty message

Revision ID: 24b22ab4772a
Revises: 5e744c87b9a7
Create Date: 2019-10-26 20:33:29.719564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24b22ab4772a"
down_revision = "5e744c87b9a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prereq", sa.Column("cid", sa.Integer(), nullable=False))
    op.drop_constraint("prereq_course_id_fkey", "prereq", type_="foreignkey")
    op.create_foreign_key(None, "prereq", "course", ["cid"], ["cid"])
    op.drop_column("prereq", "course_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prereq",
        sa.Column("course_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "prereq", type_="foreignkey")
    op.create_foreign_key(
        "prereq_course_id_fkey", "prereq", "course", ["course_id"], ["cid"]
    )
    op.drop_column("prereq", "cid")
    # ### end Alembic commands ###
