"""empty message

Revision ID: 38052c9e3378
Revises: af355807ee32
Create Date: 2019-11-07 09:41:34.801917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38052c9e3378"
down_revision = "af355807ee32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("position", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "position")
    # ### end Alembic commands ###
