"""empty message

Revision ID: 513f270c025c
Revises: 
Create Date: 2019-12-30 22:02:28.740090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "513f270c025c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "difficulty",
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("cid", "user_id"),
    )
    op.create_table(
        "quality",
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("cid", "user_id"),
    )
    op.create_table(
        "timespent",
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("cid", "user_id"),
    )
    op.add_column("course", sa.Column("position", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "position")
    op.drop_table("timespent")
    op.drop_table("quality")
    op.drop_table("difficulty")
    # ### end Alembic commands ###
