"""empty message

Revision ID: 5e744c87b9a7
Revises: 2c997df46be1
Create Date: 2019-10-26 20:31:53.926002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e744c87b9a7"
down_revision = "2c997df46be1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prereq",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("req_id", sa.Integer(), nullable=False),
        sa.Column("req_group", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["course.cid"]),
        sa.PrimaryKeyConstraint("course_id", "req_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prereq")
    # ### end Alembic commands ###
