"""empty message

Revision ID: 7062c47ffeba
Revises: 
Create Date: 2019-11-01 13:11:59.331197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7062c47ffeba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructor", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("cid"),
        sa.UniqueConstraint("cid"),
    )
    op.create_table(
        "user",
        sa.Column("internal_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("internal_id", "id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "prereq",
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("req_id", sa.Integer(), nullable=False),
        sa.Column("req_group", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"]),
        sa.PrimaryKeyConstraint("cid", "req_id"),
        sa.UniqueConstraint("cid", "req_id", "req_group", name="unique_prereq"),
    )
    op.create_table(
        "quality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id", "cid", "user_id"),
        sa.UniqueConstraint("cid", "user_id", name="unique_quality"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quality")
    op.drop_table("prereq")
    op.drop_table("user")
    op.drop_table("course")
    # ### end Alembic commands ###
