"""empty message

Revision ID: 74b0bc81c6cf
Revises: af32aa021d67
Create Date: 2019-10-10 14:31:26.796417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74b0bc81c6cf"
down_revision = "af32aa021d67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("cid", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "course", ["cid"])
    op.drop_column("course", "number")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("number", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_constraint(None, "course", type_="unique")
    op.drop_column("course", "cid")
    # ### end Alembic commands ###
