"""empty message

Revision ID: 796b983e069b
Revises: 513f270c025c
Create Date: 2021-05-09 07:56:38.116174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796b983e069b'
down_revision = '513f270c025c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor', sa.String(length=256), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('cid')
    )
    op.create_table('user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('difficulty',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['course.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cid', 'user_id')
    )
    op.create_table('prereq',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('req_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['course.cid'], ),
    sa.PrimaryKeyConstraint('cid', 'req_id'),
    sa.UniqueConstraint('cid', 'req_id', 'req_group', name='unique_prereq')
    )
    op.create_table('quality',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['course.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cid', 'user_id')
    )
    op.create_table('timespent',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['course.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cid', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timespent')
    op.drop_table('quality')
    op.drop_table('prereq')
    op.drop_table('difficulty')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
