"""empty message

Revision ID: 7ab7b47bbcdf
Revises: dea678a08b12
Create Date: 2019-11-02 17:47:03.616654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ab7b47bbcdf"
down_revision = "dea678a08b12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quality", "id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quality", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
