"""empty message

Revision ID: af32aa021d67
Revises: 
Create Date: 2019-10-10 14:28:19.314842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af32aa021d67"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructor", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("number"),
        sa.UniqueConstraint("number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course")
    # ### end Alembic commands ###
