"""empty message

Revision ID: af355807ee32
Revises: fc286b00ab87
Create Date: 2019-11-04 15:53:53.985965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af355807ee32"
down_revision = "fc286b00ab87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "difficulty",
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("cid", "user_id"),
    )
    op.create_table(
        "quality",
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("cid", "user_id"),
    )
    op.create_table(
        "timespent",
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("cid", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["cid"], ["course.cid"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("cid", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timespent")
    op.drop_table("quality")
    op.drop_table("difficulty")
    # ### end Alembic commands ###
