"""empty message

Revision ID: dea678a08b12
Revises: ac6f7fddbbe5
Create Date: 2019-11-02 17:38:20.751476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dea678a08b12"
down_revision = "ac6f7fddbbe5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_quality", "quality", type_="unique")
    op.create_unique_constraint("unique_quality", "quality", ["cid", "user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_quality", "quality", type_="unique")
    op.create_unique_constraint("unique_quality", "quality", ["id", "cid", "user_id"])
    # ### end Alembic commands ###
