"""empty message

Revision ID: fb6c9760932a
Revises: 24b22ab4772a
Create Date: 2019-10-26 20:43:18.455717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb6c9760932a"
down_revision = "24b22ab4772a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_component_commit", "prereq", ["cid", "req_id", "req_group"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_component_commit", "prereq", type_="unique")
    # ### end Alembic commands ###
