"""empty message

Revision ID: fc286b00ab87
Revises: 430f42742650
Create Date: 2019-11-04 15:53:36.091402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc286b00ab87"
down_revision = "430f42742650"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "course", ["cid"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "course", type_="unique")
    # ### end Alembic commands ###
